//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hypnofrog.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings.
        /// </summary>
        public static string accountsettings {
            get {
                return ResourceManager.GetString("accountsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievments: .
        /// </summary>
        public static string Achievments {
            get {
                return ResourceManager.GetString("Achievments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add page.
        /// </summary>
        public static string addpage {
            get {
                return ResourceManager.GetString("addpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Site.
        /// </summary>
        public static string addsite {
            get {
                return ResourceManager.GetString("addsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string columns {
            get {
                return ResourceManager.GetString("columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comments bar?.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation! You got an achievment: .
        /// </summary>
        public static string congrats {
            get {
                return ResourceManager.GetString("congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string deleteaccount {
            get {
                return ResourceManager.GetString("deleteaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write 100 sites.
        /// </summary>
        public static string descRUHas100Sites {
            get {
                return ResourceManager.GetString("descRUHas100Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set five ratings with ones.
        /// </summary>
        public static string descRUHasFiveRatingWithOnes {
            get {
                return ResourceManager.GetString("descRUHasFiveRatingWithOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set on rating.
        /// </summary>
        public static string descRUHasOneRating {
            get {
                return ResourceManager.GetString("descRUHasOneRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have one site.
        /// </summary>
        public static string descRUHasOneSite {
            get {
                return ResourceManager.GetString("descRUHasOneSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 10 rating with 5 stars.
        /// </summary>
        public static string descRUHasTenRatingsWith5Stars {
            get {
                return ResourceManager.GetString("descRUHasTenRatingsWith5Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write ten wites.
        /// </summary>
        public static string descRUHasTenSites {
            get {
                return ResourceManager.GetString("descRUHasTenSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have 10 tags on your site.
        /// </summary>
        public static string descRUHasTenTags {
            get {
                return ResourceManager.GetString("descRUHasTenTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have three sites.
        /// </summary>
        public static string descRUHasThreeSites {
            get {
                return ResourceManager.GetString("descRUHasThreeSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have three sites with rating greater than three.
        /// </summary>
        public static string descRUHasThreeSitesWithRatesGreaterThanThree {
            get {
                return ResourceManager.GetString("descRUHasThreeSitesWithRatesGreaterThanThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you think that someone here is not right, do not write - we do not care..
        /// </summary>
        public static string errordontcare {
            get {
                return ResourceManager.GetString("errordontcare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home.
        /// </summary>
        public static string errorgotomain {
            get {
                return ResourceManager.GetString("errorgotomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested page has never been on our site, or it was removed..
        /// </summary>
        public static string errornopage {
            get {
                return ResourceManager.GetString("errornopage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are done!.
        /// </summary>
        public static string errorwearedone {
            get {
                return ResourceManager.GetString("errorwearedone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famehall.
        /// </summary>
        public static string Famehall {
            get {
                return ResourceManager.GetString("Famehall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, .
        /// </summary>
        public static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string horizontal {
            get {
                return ResourceManager.GetString("horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m searching.
        /// </summary>
        public static string isearch {
            get {
                return ResourceManager.GetString("isearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give admin rules.
        /// </summary>
        public static string makeadmin {
            get {
                return ResourceManager.GetString("makeadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu placing.
        /// </summary>
        public static string Menuplacing {
            get {
                return ResourceManager.GetString("Menuplacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        public static string mixed {
            get {
                return ResourceManager.GetString("mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superman.
        /// </summary>
        public static string nameHas100Sites {
            get {
                return ResourceManager.GetString("nameHas100Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Dartan&apos;an.
        /// </summary>
        public static string nameHasFiveRatingWithOnes {
            get {
                return ResourceManager.GetString("nameHasFiveRatingWithOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a coin.
        /// </summary>
        public static string nameHasOneRating {
            get {
                return ResourceManager.GetString("nameHasOneRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Step.
        /// </summary>
        public static string nameHasOneSite {
            get {
                return ResourceManager.GetString("nameHasOneSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No principals.
        /// </summary>
        public static string nameHasTenRatingsWith5Stars {
            get {
                return ResourceManager.GetString("nameHasTenRatingsWith5Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batman.
        /// </summary>
        public static string nameHasTenSites {
            get {
                return ResourceManager.GetString("nameHasTenSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivarius.
        /// </summary>
        public static string nameHasTenTags {
            get {
                return ResourceManager.GetString("nameHasTenTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second step.
        /// </summary>
        public static string nameHasThreeSites {
            get {
                return ResourceManager.GetString("nameHasThreeSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Great Whales.
        /// </summary>
        public static string nameHasThreeSitesWithRatesGreaterThanThree {
            get {
                return ResourceManager.GetString("nameHasThreeSitesWithRatesGreaterThanThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No menu.
        /// </summary>
        public static string nomenu {
            get {
                return ResourceManager.GetString("nomenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating: .
        /// </summary>
        public static string rating {
            get {
                return ResourceManager.GetString("rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites and content.
        /// </summary>
        public static string siteandcontent {
            get {
                return ResourceManager.GetString("siteandcontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites added: .
        /// </summary>
        public static string sitesadded {
            get {
                return ResourceManager.GetString("sitesadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site settings.
        /// </summary>
        public static string sitesettings {
            get {
                return ResourceManager.GetString("sitesettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can set up your site and its first page..
        /// </summary>
        public static string sitesettingsdesc {
            get {
                return ResourceManager.GetString("sitesettingsdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Sites.
        /// </summary>
        public static string TopSites {
            get {
                return ResourceManager.GetString("TopSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to access.
        /// </summary>
        public static string urltoaccess {
            get {
                return ResourceManager.GetString("urltoaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string vertivcal {
            get {
                return ResourceManager.GetString("vertivcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
    }
}
