//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Creditals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Creditals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hypnofrog.Strings.Creditals", typeof(Creditals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is not valid..
        /// </summary>
        public static string AccountController_Login_This_email_is_not_valid_ {
            get {
                return ResourceManager.GetString("AccountController_Login_This_email_is_not_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dldmfb5fo.
        /// </summary>
        public static string CloudinaryAccount {
            get {
                return ResourceManager.GetString("CloudinaryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZO4nwcMQwcT88lUNUK5KHJmy_fU.
        /// </summary>
        public static string CloudinaryHash {
            get {
                return ResourceManager.GetString("CloudinaryHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 568721824454478.
        /// </summary>
        public static string CloudinaryPassword {
            get {
                return ResourceManager.GetString("CloudinaryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Do_not_match {
            get {
                return ResourceManager.GetString("Do_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не подтверждён..
        /// </summary>
        public static string Email_not_confirmed {
            get {
                return ResourceManager.GetString("Email_not_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your own template can`t be null!.
        /// </summary>
        public static string HomeController_CreateWithTemplate {
            get {
                return ResourceManager.GetString("HomeController_CreateWithTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://i493.photobucket.com/albums/rr299/0khi/Futurama/hypnofrog.gif.
        /// </summary>
        public static string HypnoPhoto {
            get {
                return ResourceManager.GetString("HypnoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/_Layout.cshtml.
        /// </summary>
        public static string LayoutHM {
            get {
                return ResourceManager.GetString("LayoutHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/_LayoutVM.cshtml.
        /// </summary>
        public static string LayoutVM {
            get {
                return ResourceManager.GetString("LayoutVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/_LayoutWM.cshtml.
        /// </summary>
        public static string LayoutWM {
            get {
                return ResourceManager.GetString("LayoutWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин и пароль..
        /// </summary>
        public static string Login_Enter_login_or_password {
            get {
                return ResourceManager.GetString("Login_Enter_login_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль..
        /// </summary>
        public static string Login_Not_valid_login {
            get {
                return ResourceManager.GetString("Login_Not_valid_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid user name(it should contains only letters and numbers)..
        /// </summary>
        public static string Register_Not_valid_user_name_rules {
            get {
                return ResourceManager.GetString("Register_Not_valid_user_name_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string RegisterViewModel_Name_rules {
            get {
                return ResourceManager.GetString("RegisterViewModel_Name_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string Remember_this_browser {
            get {
                return ResourceManager.GetString("Remember_this_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string VerifyCode_Invalid_code {
            get {
                return ResourceManager.GetString("VerifyCode_Invalid_code", resourceCulture);
            }
        }
    }
}
