// <auto-generated />
namespace Hypnofrog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReturnContent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReturnContent));
        
        string IMigrationMetadata.Id
        {
            get { return "201608031226542_Return Content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
